export const GET_ALL_CONTACTS = "GET_ALL_CONTACTS";
export const CREATE_CONTACT = "CREATE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const NAME = "NAME";
export const PHONE_NUMBER = "PHONE_NUMBER";